version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn gamp_gateway.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --timeout 60 --log-level=info
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      - DATABASE=postgres

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:6-alpine

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A gamp_gateway worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A gamp_gateway beat --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data: