# Generated by Django 4.2.13 on 2024-07-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamp_auth', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
