# Generated by Django 4.2.13 on 2024-07-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamp_auth', '0003_user_old_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('message_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('response_metadata', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
