# Generated by Django 4.2.13 on 2024-07-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamp_auth', '0004_otplog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otplog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'OTP Log', 'verbose_name_plural': 'OTP Logs'},
        ),
    ]
